export const PUBLIC_ROUTES = [
	// "/",
	// "/admin",
	// "/app/create-shop",
	// "/app/manage-store",
	// "/app",
	"/app/cart",
	"/app/products",
	"/app/real-estate",
	"/login",
	"/register",
	"/reset-password",
	"/verify-otp",
	"/forgot-password",
	"/activate-account",
	"/politique-de-confidentialite",
	"/termes-et-conditions",
];
